/*
 Navicat Premium Dump SQL

 Source Server         : DaunPenh Postgresql
 Source Server Type    : PostgreSQL
 Source Server Version : 140018 (140018)
 Source Host           : 157.10.73.52:5432
 Source Catalog        : plp_mentoring_sovath
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 140018 (140018)
 File Encoding         : 65001

 Date: 08/08/2025 22:48:34
*/


-- ----------------------------
-- Table structure for master_fields_123
-- ----------------------------
DROP TABLE IF EXISTS "public"."master_fields_123";
CREATE TABLE "public"."master_fields_123" (
  "id" int4 NOT NULL,
  "order" int4,
  "subject" varchar(512) COLLATE "pg_catalog"."default",
  "grade" varchar(512) COLLATE "pg_catalog"."default",
  "level" varchar(512) COLLATE "pg_catalog"."default",
  "field_type_one" varchar(512) COLLATE "pg_catalog"."default",
  "field_type_two" varchar(512) COLLATE "pg_catalog"."default",
  "field_type_three" varchar(512) COLLATE "pg_catalog"."default",
  "field_type_four" varchar(512) COLLATE "pg_catalog"."default",
  "activity" varchar(512) COLLATE "pg_catalog"."default",
  "indicator" varchar(512) COLLATE "pg_catalog"."default",
  "note" varchar(512) COLLATE "pg_catalog"."default"
)
;
ALTER TABLE "public"."master_fields_123" OWNER TO "admin";

-- ----------------------------
-- Records of master_fields_123
-- ----------------------------
BEGIN;
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (2, 2, 'KH', 'G1', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ១៖ ការស្គាល់សូរអក្សរថ្មី', '១. ប្រើប្រាស់សៀវភៅណែនាំគ្រូ(អនុវតជំហានសកម្មភាពតាមលំដាប់លំដោយ) ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (3, 3, 'KH', 'G1', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ១៖ ការស្គាល់សូរអក្សរថ្មី', '២. ធ្វើតាមលំនាំគ្រូធ្វើគ្រូនិង​សិស្សធ្វើ សិស្សធ្វើ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (4, 4, 'KH', 'G1', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ១៖ ការស្គាល់សូរអក្សរថ្មី', '៣. អនុវត្តតាមពេលវេលាកំណត់ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (5, 5, 'KH', 'G1', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ២៖ ការស្គាល់តួអក្សរថ្មី', '១. ប្រើប្រាស់សៀវភៅណែនាំគ្រូ(អនុវតជំហានសកម្មភាពតាមលំដាប់លំដោយ) ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (6, 6, 'KH', 'G1', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ២៖ ការស្គាល់តួអក្សរថ្មី', '២. ធ្វើតាមលំនាំគ្រូធ្វើគ្រូនិង​សិស្សធ្វើ សិស្សធ្វើ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (7, 7, 'KH', 'G1', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ២៖ ការស្គាល់តួអក្សរថ្មី', '៥. ដើរតាមតុ ពិនិត្យ ការសរសេរ ឬការអានរបស់សិស្ស ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (8, 8, 'KH', 'G1', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៣a៖ ការអានព្យាង្គ', '១. ប្រើប្រាស់សៀវភៅណែនាំគ្រូ(អនុវតជំហានសកម្មភាពតាមលំដាប់លំដោយ) ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (9, 9, 'KH', 'G1', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៣a៖ ការអានព្យាង្គ', '២. ធ្វើតាមលំនាំគ្រូធ្វើគ្រូនិង​សិស្សធ្វើ សិស្សធ្វើ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (10, 10, 'KH', 'G1', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៣a៖ ការអានព្យាង្គ', '៤. ឱ្យសិស្សអានដោយប្រើចង្អុលដៃអូសពីក្រោម និង សម្លឹងមើលតួអក្សរដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (11, 11, 'KH', 'G1', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៣a៖ ការអានព្យាង្គ', '៥. ដើរតាមតុ ពិនិត្យ ការសរសេរ ឬការអានរបស់សិស្ស ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (12, 12, 'KH', 'G1', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៣b៖ ការអានពាក្យ', '១. ប្រើប្រាស់សៀវភៅណែនាំគ្រូ(អនុវតជំហានសកម្មភាពតាមលំដាប់លំដោយ) ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (13, 13, 'KH', 'G1', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៣b៖ ការអានពាក្យ', '២. ធ្វើតាមលំនាំគ្រូធ្វើគ្រូនិង​សិស្សធ្វើ សិស្សធ្វើ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (14, 14, 'KH', 'G1', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៣b៖ ការអានពាក្យ', '៤. ឱ្យសិស្សអានដោយប្រើចង្អុលដៃអូសពីក្រោម និង សម្លឹងមើលតួអក្សរដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (15, 15, 'KH', 'G1', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៣b៖ ការអានពាក្យ', '៥. ដើរតាមតុ ពិនិត្យ ការសរសេរ ឬការអានរបស់សិស្ស ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (16, 16, 'KH', 'G1', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៤៖ វាក្យសព្ទ', '១. ប្រើប្រាស់សៀវភៅណែនាំគ្រូ(អនុវតជំហានសកម្មភាពតាមលំដាប់លំដោយ) ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (17, 17, 'KH', 'G1', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៤៖ វាក្យសព្ទ', '២. ធ្វើតាមលំនាំគ្រូធ្វើគ្រូនិង​សិស្សធ្វើ សិស្សធ្វើ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (18, 18, 'KH', 'G1', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៥៖ ការអានល្បះ (មិនមានក្នុងមេរៀនស្ពានទេ)', '១. ប្រើប្រាស់សៀវភៅណែនាំគ្រូ(អនុវតជំហានសកម្មភាពតាមលំដាប់លំដោយ) ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (19, 19, 'KH', 'G1', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៥៖ ការអានល្បះ (មិនមានក្នុងមេរៀនស្ពានទេ)', '២. ធ្វើតាមលំនាំគ្រូធ្វើគ្រូនិង​សិស្សធ្វើ សិស្សធ្វើ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (20, 20, 'KH', 'G1', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៥៖ ការអានល្បះ (មិនមានក្នុងមេរៀនស្ពានទេ)', '៤. ឱ្យសិស្សអានដោយប្រើចង្អុលដៃអូសពីក្រោម និង សម្លឹងមើលតួអក្សរដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (21, 21, 'KH', 'G1', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៥៖ ការអានល្បះ (មិនមានក្នុងមេរៀនស្ពានទេ)', '៥. ដើរតាមតុ ពិនិត្យ ការសរសេរ ឬការអានរបស់សិស្ស ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (22, 22, 'KH', 'G1', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៦៖ ការអានអត្ថបទខ្លី', '១. ប្រើប្រាស់សៀវភៅណែនាំគ្រូ(អនុវតជំហានសកម្មភាពតាមលំដាប់លំដោយ) ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (23, 23, 'KH', 'G1', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៦៖ ការអានអត្ថបទខ្លី', '២. ធ្វើតាមលំនាំគ្រូធ្វើគ្រូនិង​សិស្សធ្វើ សិស្សធ្វើ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (24, 24, 'KH', 'G1', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៦៖ ការអានអត្ថបទខ្លី', '៤. ឱ្យសិស្សអានដោយប្រើចង្អុលដៃអូសពីក្រោម និង សម្លឹងមើលតួអក្សរដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (25, 25, 'KH', 'G1', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៦៖ ការអានអត្ថបទខ្លី', '៥. ដើរតាមតុ ពិនិត្យ ការសរសេរ ឬការអានរបស់សិស្ស ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (26, 26, 'KH', 'G1', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៧៖ ការសរសេរ', '១. ប្រើប្រាស់សៀវភៅណែនាំគ្រូ(អនុវតជំហានសកម្មភាពតាមលំដាប់លំដោយ) ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (27, 27, 'KH', 'G1', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៧៖ ការសរសេរ', '២. ធ្វើតាមលំនាំគ្រូធ្វើគ្រូនិង​សិស្សធ្វើ សិស្សធ្វើ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (28, 28, 'KH', 'G1', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៧៖ ការសរសេរ', '៥. ដើរតាមតុ ពិនិត្យ ការសរសេរ ឬការអានរបស់សិស្ស ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (29, 1, 'KH', 'G1', 'LEVEL-2', 'radio', NULL, NULL, 'text', 'ការរំឭកមេរៀន (គ្រូអាចមិនប្រើអក្សរដិតក្នុងសៀវភៅបាន)', '៦. ប្រើពាក្យ ដែលសរសេរជាអក្សរដិត ក្នុងសៀវភៅណែនាំគ្រូ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (30, 2, 'KH', 'G1', 'LEVEL-2', 'radio', NULL, NULL, 'text', 'សកម្មភាព ១៖ ការស្គាល់សូរអក្សរថ្មី', '៦. ប្រើពាក្យ ដែលសរសេរជាអក្សរដិត ក្នុងសៀវភៅណែនាំគ្រូ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (31, 3, 'KH', 'G1', 'LEVEL-2', 'radio', NULL, NULL, 'text', 'សកម្មភាព ២៖ ការស្គាល់តួអក្សរថ្មី', '៦. ប្រើពាក្យ ដែលសរសេរជាអក្សរដិត ក្នុងសៀវភៅណែនាំគ្រូ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (32, 4, 'KH', 'G1', 'LEVEL-2', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៣a៖ ការអានព្យាង្គ', '៦. ប្រើពាក្យ ដែលសរសេរជាអក្សរដិត ក្នុងសៀវភៅណែនាំគ្រូ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (33, 5, 'KH', 'G1', 'LEVEL-2', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៣a៖ ការអានព្យាង្គ', '៧. ឱ្យសិស្សអានច្រើនដង (ទាំងការអានជាមួយដៃគូ ឬអានដោយខ្លួនឯង) ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (34, 6, 'KH', 'G1', 'LEVEL-2', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៣b៖ ការអានពាក្យ', '៦. ប្រើពាក្យ ដែលសរសេរជាអក្សរដិត ក្នុងសៀវភៅណែនាំគ្រូ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (35, 7, 'KH', 'G1', 'LEVEL-2', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៣b៖ ការអានពាក្យ', '៧. ឱ្យសិស្សអានច្រើនដង (ទាំងការអានជាមួយដៃគូ ឬអានដោយខ្លួនឯង) ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (36, 8, 'KH', 'G1', 'LEVEL-2', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៤៖ វាក្យសព្ទ', '៦. ប្រើពាក្យ ដែលសរសេរជាអក្សរដិត ក្នុងសៀវភៅណែនាំគ្រូ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (37, 9, 'KH', 'G1', 'LEVEL-2', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៥៖ ការអានល្បះ (មិនមានក្នុងមេរៀនស្ពានទេ)', '៦. ប្រើពាក្យ ដែលសរសេរជាអក្សរដិត ក្នុងសៀវភៅណែនាំគ្រូ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (38, 10, 'KH', 'G1', 'LEVEL-2', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៥៖ ការអានល្បះ (មិនមានក្នុងមេរៀនស្ពានទេ)', '៧. ឱ្យសិស្សអានច្រើនដង (ទាំងការអានជាមួយដៃគូ ឬអានដោយខ្លួនឯង) ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (39, 11, 'KH', 'G1', 'LEVEL-2', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៦៖ ការអានអត្ថបទខ្លី', '៦. ប្រើពាក្យ ដែលសរសេរជាអក្សរដិត ក្នុងសៀវភៅណែនាំគ្រូ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (40, 12, 'KH', 'G1', 'LEVEL-2', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៦៖ ការអានអត្ថបទខ្លី', '៧. ឱ្យសិស្សអានច្រើនដង (ទាំងការអានជាមួយដៃគូ ឬអានដោយខ្លួនឯង) ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (41, 13, 'KH', 'G1', 'LEVEL-2', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៧៖ ការសរសេរ', '៦. ប្រើពាក្យ ដែលសរសេរជាអក្សរដិត ក្នុងសៀវភៅណែនាំគ្រូ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (42, 1, 'KH', 'G1', 'LEVEL-3', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៣a៖ ការអានព្យាង្គ', '១០. ដើរតាមតុ រួចឈប់ ដើម្បីស្ដាប់សិស្សអាន ហើយជួយសិស្ស ដែលពិបាកអាន ដែរឬទេ?​', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (43, 2, 'KH', 'G1', 'LEVEL-3', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៣b៖ ការអានពាក្យ', '១០. ដើរតាមតុ រួចឈប់ ដើម្បីស្ដាប់សិស្សអាន ហើយជួយសិស្ស ដែលពិបាកអាន ដែរឬទេ?​', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (44, 3, 'KH', 'G1', 'LEVEL-3', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៥៖ ការអានល្បះ (មិនមានក្នុងមេរៀនស្ពានទេ)', '១០. ដើរតាមតុ រួចឈប់ ដើម្បីស្ដាប់សិស្សអាន ហើយជួយសិស្ស ដែលពិបាកអាន ដែរឬទេ?​', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (45, 4, 'KH', 'G1', 'LEVEL-3', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៦៖ ការអានអត្ថបទខ្លី', '១០. ដើរតាមតុ រួចឈប់ ដើម្បីស្ដាប់សិស្សអាន ហើយជួយសិស្ស ដែលពិបាកអាន ដែរឬទេ?​', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (46, 1, 'KH', 'G2', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'ការរំឭកមេរៀន (ឆមាសទី១)', '១. ប្រើប្រាស់សៀវភៅណែនាំគ្រូ(អនុវត្តជំហានសកម្មភាពតាមលំដាប់លំដោយ) ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (47, 2, 'KH', 'G2', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ១៖ ការស្គាល់សូរអក្សរថ្មី(ឆមាសទី១)', '១. ប្រើប្រាស់សៀវភៅណែនាំគ្រូ(អនុវត្តជំហានសកម្មភាពតាមលំដាប់លំដោយ) ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (130, 26, 'MATH', 'G1,G2,G3', 'LEVEL-2', 'radio', NULL, NULL, 'text', '៤. ការវាយតម្លៃ-៤.៣ កម្រិតសំណួរ  ', 'សិស្សឆ្លើយបានត្រឹមសំណួរកម្រិតយល់ដឹង', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (48, 3, 'KH', 'G2', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ១៖ ការស្គាល់សូរអក្សរថ្មី(ឆមាសទី១)', '២. ធ្វើតាមលំនាំគ្រូធ្វើគ្រូនិងសិស្សធ្វើ សិស្សធ្វើ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (49, 4, 'KH', 'G2', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ១៖ ការស្គាល់សូរអក្សរថ្មី(ឆមាសទី១)', '៣. អនុវត្តតាមពេលវេលាកំណត់ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (50, 5, 'KH', 'G2', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព២៖ការស្គាល់តួអក្សរថ្មី(ឆមាសទី១)', '១. ប្រើប្រាស់សៀវភៅណែនាំគ្រូ(អនុវត្តជំហានសកម្មភាពតាមលំដាប់លំដោយ) ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (51, 6, 'KH', 'G2', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព២៖ការស្គាល់តួអក្សរថ្មី(ឆមាសទី១)', '២. ធ្វើតាមលំនាំគ្រូធ្វើគ្រូនិងសិស្សធ្វើ សិស្សធ្វើ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (52, 7, 'KH', 'G2', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព២៖ការស្គាល់តួអក្សរថ្មី(ឆមាសទី១)', '៥. ដើរតាមតុ និងពិនិត្យការសរសេរ ឬការអានរបស់សិស្ស ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (53, 8, 'KH', 'G2', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៣a៖ ការអានព្យាង្គ (ឆមាសទី១)', '១. ប្រើប្រាស់សៀវភៅណែនាំគ្រូ(អនុវត្តជំហានសកម្មភាពតាមលំដាប់លំដោយ) ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (54, 9, 'KH', 'G2', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៣a៖ ការអានព្យាង្គ (ឆមាសទី១)', '២. ធ្វើតាមលំនាំគ្រូធ្វើគ្រូនិងសិស្សធ្វើ សិស្សធ្វើ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (55, 10, 'KH', 'G2', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៣a៖ ការអានព្យាង្គ (ឆមាសទី១)', '៤. ឱ្យសិស្សអានដោយប្រើចង្អុលដៃអូសពីក្រោម និង សម្លឹងមើលតួអក្សរដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (56, 11, 'KH', 'G2', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៣a៖ ការអានព្យាង្គ (ឆមាសទី១)', '៥. ដើរតាមតុ និងពិនិត្យការសរសេរ ឬការអានរបស់សិស្ស ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (57, 12, 'KH', 'G2', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៤៖ វាក្យសព្ទ (ឆមាសទី១ & ២)', '១. ប្រើប្រាស់សៀវភៅណែនាំគ្រូ(អនុវត្តជំហានសកម្មភាពតាមលំដាប់លំដោយ) ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (58, 13, 'KH', 'G2', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៤៖ វាក្យសព្ទ (ឆមាសទី១ & ២)', '២. ធ្វើតាមលំនាំគ្រូធ្វើគ្រូនិងសិស្សធ្វើ សិស្សធ្វើ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (59, 14, 'KH', 'G2', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៤៖ វាក្យសព្ទ (ឆមាសទី១ & ២)', '៤. ឱ្យសិស្សអានដោយប្រើចង្អុលដៃអូសពីក្រោម និង សម្លឹងមើលតួអក្សរដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (60, 15, 'KH', 'G2', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៤៖ វាក្យសព្ទ (ឆមាសទី១ & ២)', '៥. ដើរតាមតុ និងពិនិត្យការសរសេរ ឬការអានរបស់សិស្ស ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (61, 16, 'KH', 'G2', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៥៖ ការអានល្បះ (ឆមាសទី១)', '១. ប្រើប្រាស់សៀវភៅណែនាំគ្រូ(អនុវត្តជំហានសកម្មភាពតាមលំដាប់លំដោយ) ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (62, 17, 'KH', 'G2', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៥៖ ការអានល្បះ (ឆមាសទី១)', '២. ធ្វើតាមលំនាំគ្រូធ្វើគ្រូនិងសិស្សធ្វើ សិស្សធ្វើ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (63, 18, 'KH', 'G2', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៥៖ ការអានល្បះ (ឆមាសទី១)', '៤. ឱ្យសិស្សអានដោយប្រើចង្អុលដៃអូសពីក្រោម និង សម្លឹងមើលតួអក្សរដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (64, 19, 'KH', 'G2', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៥៖ ការអានល្បះ (ឆមាសទី១)', '៥. ដើរតាមតុ និងពិនិត្យការសរសេរ ឬការអានរបស់សិស្ស ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (65, 20, 'KH', 'G2', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៦៖ ការអានអត្ថបទខ្លី(ឆមាសទី១ & ២)', '១. ប្រើប្រាស់សៀវភៅណែនាំគ្រូ(អនុវត្តជំហានសកម្មភាពតាមលំដាប់លំដោយ) ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (66, 21, 'KH', 'G2', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៦៖ ការអានអត្ថបទខ្លី(ឆមាសទី១ & ២)', '២. ធ្វើតាមលំនាំគ្រូធ្វើគ្រូនិងសិស្សធ្វើ សិស្សធ្វើ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (67, 22, 'KH', 'G2', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៦៖ ការអានអត្ថបទខ្លី(ឆមាសទី១ & ២)', '៤. ឱ្យសិស្សអានដោយប្រើចង្អុលដៃអូសពីក្រោម និង សម្លឹងមើលតួអក្សរដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (68, 23, 'KH', 'G2', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៦៖ ការអានអត្ថបទខ្លី(ឆមាសទី១ & ២)', '៥. ដើរតាមតុ និងពិនិត្យការសរសេរ ឬការអានរបស់សិស្ស ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (69, 24, 'KH', 'G2', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៧៖ ការសរសេរ (ឆមាសទី១&២)', '១. ប្រើប្រាស់សៀវភៅណែនាំគ្រូ(អនុវត្តជំហានសកម្មភាពតាមលំដាប់លំដោយ) ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (70, 25, 'KH', 'G2', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៧៖ ការសរសេរ (ឆមាសទី១&២)', '២. ធ្វើតាមលំនាំគ្រូធ្វើគ្រូនិងសិស្សធ្វើ សិស្សធ្វើ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (71, 26, 'KH', 'G2', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៧៖ ការសរសេរ (ឆមាសទី១&២)', '៥. ដើរតាមតុ និងពិនិត្យការសរសេរ ឬការអានរបស់សិស្ស ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (72, 1, 'KH', 'G2', 'LEVEL-2', 'radio', NULL, NULL, 'text', 'ការរំឭកមេរៀន (គ្រូអាចមិនប្រើអក្សរដិតក្នុងសៀវភៅបាន)', '៦. ប្រើពាក្យ ដែលសរសេរជាអក្សរដិត ក្នុងសៀវភៅណែនាំគ្រូ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (73, 2, 'KH', 'G2', 'LEVEL-2', 'radio', NULL, NULL, 'text', 'សកម្មភាព ១៖ ការស្គាល់សូរអក្សរថ្មី', '៦. ប្រើពាក្យ ដែលសរសេរជាអក្សរដិត ក្នុងសៀវភៅណែនាំគ្រូ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (74, 3, 'KH', 'G2', 'LEVEL-2', 'radio', NULL, NULL, 'text', 'សកម្មភាព ២៖ ការស្គាល់តួអក្សរថ្មី', '៦. ប្រើពាក្យ ដែលសរសេរជាអក្សរដិត ក្នុងសៀវភៅណែនាំគ្រូ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (75, 4, 'KH', 'G2', 'LEVEL-2', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៣a៖ ការអានព្យាង្គ', '៦. ប្រើពាក្យ ដែលសរសេរជាអក្សរដិត ក្នុងសៀវភៅណែនាំគ្រូ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (76, 5, 'KH', 'G2', 'LEVEL-2', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៣a៖ ការអានព្យាង្គ', '៧. ឱ្យសិស្សអានច្រើនដង (ទាំងការអានជាមួយដៃគូ ឬអានដោយខ្លួនឯង) ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (77, 6, 'KH', 'G2', 'LEVEL-2', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៣b៖ ការអានពាក្យ', '៦. ប្រើពាក្យ ដែលសរសេរជាអក្សរដិត ក្នុងសៀវភៅណែនាំគ្រូ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (78, 7, 'KH', 'G2', 'LEVEL-2', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៣b៖ ការអានពាក្យ', '៧. ឱ្យសិស្សអានច្រើនដង (ទាំងការអានជាមួយដៃគូ ឬអានដោយខ្លួនឯង) ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (79, 8, 'KH', 'G2', 'LEVEL-2', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៤៖ វាក្យសព្ទ', '៦. ប្រើពាក្យ ដែលសរសេរជាអក្សរដិត ក្នុងសៀវភៅណែនាំគ្រូ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (80, 9, 'KH', 'G2', 'LEVEL-2', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៥៖ ការអានល្បះ (មិនមានក្នុងមេរៀនស្ពានទេ)', '៦. ប្រើពាក្យ ដែលសរសេរជាអក្សរដិត ក្នុងសៀវភៅណែនាំគ្រូ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (81, 10, 'KH', 'G2', 'LEVEL-2', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៥៖ ការអានល្បះ (មិនមានក្នុងមេរៀនស្ពានទេ)', '៧. ឱ្យសិស្សអានច្រើនដង (ទាំងការអានជាមួយដៃគូ ឬអានដោយខ្លួនឯង) ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (82, 11, 'KH', 'G2', 'LEVEL-2', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៦៖ ការអានអត្ថបទខ្លី', '៦. ប្រើពាក្យ ដែលសរសេរជាអក្សរដិត ក្នុងសៀវភៅណែនាំគ្រូ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (83, 12, 'KH', 'G2', 'LEVEL-2', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៦៖ ការអានអត្ថបទខ្លី', '៧. ឱ្យសិស្សអានច្រើនដង (ទាំងការអានជាមួយដៃគូ ឬអានដោយខ្លួនឯង) ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (84, 13, 'KH', 'G2', 'LEVEL-2', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៧៖ ការសរសេរ', '៦. ប្រើពាក្យ ដែលសរសេរជាអក្សរដិត ក្នុងសៀវភៅណែនាំគ្រូ ដែរឬទេ?', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (85, 1, 'KH', 'G2', 'LEVEL-3', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៣a៖ ការអានព្យាង្គ', '១០. ដើរតាមតុ រួចឈប់ ដើម្បីស្ដាប់សិស្សអាន ហើយជួយសិស្ស ដែលពិបាកអាន ដែរឬទេ?​', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (86, 2, 'KH', 'G2', 'LEVEL-3', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៣b៖ ការអានពាក្យ', '១០. ដើរតាមតុ រួចឈប់ ដើម្បីស្ដាប់សិស្សអាន ហើយជួយសិស្ស ដែលពិបាកអាន ដែរឬទេ?​', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (87, 3, 'KH', 'G2', 'LEVEL-3', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៥៖ ការអានល្បះ (មិនមានក្នុងមេរៀនស្ពានទេ)', '១០. ដើរតាមតុ រួចឈប់ ដើម្បីស្ដាប់សិស្សអាន ហើយជួយសិស្ស ដែលពិបាកអាន ដែរឬទេ?​', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (88, 4, 'KH', 'G2', 'LEVEL-3', 'radio', NULL, NULL, 'text', 'សកម្មភាព ៦៖ ការអានអត្ថបទខ្លី', '១០. ដើរតាមតុ រួចឈប់ ដើម្បីស្ដាប់សិស្សអាន ហើយជួយសិស្ស ដែលពិបាកអាន ដែរឬទេ?​', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (89, 1, 'KH', 'G3', 'LEVEL-1', 'radio', 'radio', 'radio', 'text', 'ខ្លឹមសារបង្រៀន', 'ខ្លឹមសារបង្រៀនស្របតាមសកម្មភាពគោលដែលបានកំណត់ក្នុងសៀវភៅណែនាំគ្រូ', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (90, 2, 'KH', 'G3', 'LEVEL-1', 'radio', 'radio', 'radio', 'text', 'ខ្លឹមសារបង្រៀន', 'ពាក្យអក្សរដិតនៅតាមសកម្មភាពគោលនីមួយៗត្រូវបានប្រើប្រាស់ត្រឹមត្រូវតាមមេរៀននីមួយៗ', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (91, 3, 'KH', 'G3', 'LEVEL-1', 'radio', 'radio', 'radio', 'text', 'ខ្លឹមសារបង្រៀន', 'ខ្លឹមសារមេរៀនស្របតាមបំណែងចែកកម្មវិធីសិក្សា(យឺតត្រឹម២សប្តាហ៍ចាត់ទុកថាទាន់កម្មវិធី)', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (92, 4, 'KH', 'G3', 'LEVEL-2', 'radio', 'radio', 'radio', 'text', 'ការបង្រៀន', 'គ្រូបង្រៀនសកម្មភាពនីមួយៗទៅតាមពេលវេលាដែលបានកំណត់ក្នុងមេរៀននីមួយៗបានត្រឹមត្រូវ', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (93, 5, 'KH', 'G3', 'LEVEL-2', 'radio', 'radio', 'radio', 'text', 'ការបង្រៀន', 'ប្រើគោលការណ៍ គ្រូធ្វើ គ្រូនិងសិស្សធ្វើ សិស្សធ្វើ តាមសកម្មភាពដែលបានកំណត់ក្នុងសៀវភៅគ្រូ', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (94, 6, 'KH', 'G3', 'LEVEL-2', 'radio', 'radio', 'radio', 'text', 'ការបង្រៀន', 'គ្រូចល័តទៅក្រុមនានាក្នុងថ្នាក់រាល់ពេលថ្នាក់ធ្វើសកម្មភាពនិងជំរុញឱ្យសិស្សទាំងអស់ចូលរួមធ្វើសកម្មភាពតាមការណែនាំរបស់គ្រូ', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (95, 7, 'KH', 'G3', 'LEVEL-2', 'radio', 'radio', 'radio', 'text', 'ការបង្រៀន', 'មានអន្តរកម្មល្អ រវាងគ្រូនឹងសិស្ស ', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (96, 8, 'KH', 'G3', 'LEVEL-2', 'radio', 'radio', 'radio', 'text', 'ការហ្វឹកហាត់របស់សិស្ស', 'សិស្សទំាងអស់បានធ្វើសកម្មភាព អាន និយាយ ស្តាប់ សរសេរ ឬ ធ្វើលំហាត់ ជាបុគ្គល ជាដៃគូ', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (97, 9, 'KH', 'G3', 'LEVEL-2', 'radio', 'radio', 'radio', 'text', 'ការហ្វឹកហាត់របស់សិស្ស', 'សិស្សហ្វឹកហាត់ធ្វើលំហាត់ក្នុងសៀវភៅកិច្ចការផ្ទះភាសាខ្មែរឬផ្តល់កិច្ចការដែលគ្រូដាក់ឱ្យ', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (98, 10, 'KH', 'G3', 'LEVEL-3', 'radio', 'radio', 'radio', 'text', 'បរិយាកាសសិក្សា​', 'ជំរុញឱ្យសិស្សមានការផ្លាស់ប្តូរឥរិយាបថដោយលើកទឹកចិត្តសិស្ស ឱ្យចូលចិត្តអាន និយាយ ស្តាប់ និងសំណេរ', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (99, 11, 'KH', 'G3', 'LEVEL-3', 'radio', 'radio', 'radio', 'text', 'បរិយាកាសសិក្សា​', 'បណ្តុះគំនិតសិស្សឱ្យច្នៃប្រឌិតដោយការផ្សារភ្ជាប់ទៅនិងជីវភាពប្រចាំថ្ងៃ', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (100, 12, 'KH', 'G3', 'LEVEL-3', 'radio', 'radio', 'radio', 'text', 'បរិយាកាសសិក្សា​', 'ប្រើប្រាស់ ICT តាមការច្នៃប្រឌិតរបស់គ្រូ (ដូចជា ប្រើប្រាស់LCD, ធុងបាសឬប្រើប្រាស់ទូរសព្ទដៃ)', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (101, 13, 'KH', 'G3', 'LEVEL-3', 'radio', 'radio', 'radio', 'text', 'បរិយាកាសសិក្សា​', 'គ្រូលើកទឹកចិត្តឱ្យសិស្សក្លាហាន យកចិត្តទុកដាក់ សហការ ជួយគ្នា គោរពគ្នា ចែករំលែកចំណេះដឹង ចូលរួមធ្វើសកម្មភាព', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (102, 14, 'KH', 'G3', 'LEVEL-3', 'radio', 'radio', 'radio', 'text', 'ការវាយតម្លៃ', 'គ្រូចល័តក្នុងថ្នាក់ រួចឈប់ ហើយស្តាប់សិស្សអាន និងសរសេរដើម្បីកំណត់សិស្សដែលជួបការលំបាកក្នុងការអាននិងសរសេរ', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (103, 15, 'KH', 'G3', 'LEVEL-3', 'radio', 'radio', 'radio', 'text', 'ការវាយតម្លៃ', 'គ្រូពិនិត្យចំណេះដឹងរបស់សិស្សតាមរយៈការសួរសំណួរបញ្ជាក់ ឬហៅឱ្យសិស្សសរសេរ', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (104, 16, 'KH', 'G3', 'LEVEL-3', 'radio', 'radio', 'radio', 'text', 'ការវាយតម្លៃ', 'គ្រូជួយសិស្សជួបការលំបាកអាន សរសេរ នៅពេលបង្រៀន', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (105, 1, 'MATH', 'G1,G2,G3', 'LEVEL-1', 'radio', NULL, NULL, 'text', '១. ខ្លឹមសារមេរៀន', 'គ្រូមិនទាន់យល់ច្បាស់ពីខ្លឹមសារមេរៀនកំពុងបង្រៀន', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (106, 2, 'MATH', 'G1,G2,G3', 'LEVEL-2', 'radio', NULL, NULL, 'text', '១. ខ្លឹមសារមេរៀន', 'គ្រូយល់ច្បាស់ពីខ្លឹមសារមេរៀនកំពុងបង្រៀន ដែលនាំឱ្យការពន្យល់ខ្លឹមសារបានត្រឹមត្រូវ', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (107, 3, 'MATH', 'G1,G2,G3', 'LEVEL-3', 'radio', NULL, NULL, 'text', '១. ខ្លឹមសារមេរៀន', 'គ្រូញែកខ្លឹមសារមេរៀនតាមកម្រិតសមត្ថភាពរបស់សិស្ស និងផ្សារភ្ជាប់នឹងជីវភាពរស់នៅ', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (108, 4, 'MATH', 'G1,G2,G3', 'LEVEL-1', 'radio', NULL, NULL, 'text', '២. ការប្រើប្រាស់សម្ភារឧបទេសក្នុងការរៀន និងបង្រៀន-២.១ សម្ភារឧបទេសក្នុងការរៀន និងបង្រៀន', 'មិនមានសម្ភារឧបទេស ឬមានសម្ភារឧបទេសប៉ុន្តែមិនសមស្របតាមខ្លឹមសារមេរៀន​', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (109, 5, 'MATH', 'G1,G2,G3', 'LEVEL-2', 'radio', NULL, NULL, 'text', '២. ការប្រើប្រាស់សម្ភារឧបទេសក្នុងការរៀន និងបង្រៀន-២.១ សម្ភារឧបទេសក្នុងការរៀន និងបង្រៀន', 'មានសម្ភារឧបទេសងាយៗក្នុងមូលដ្ឋាន សមស្របតាមខ្លឹមសារមេរៀន', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (110, 6, 'MATH', 'G1,G2,G3', 'LEVEL-3', 'radio', NULL, NULL, 'text', '២. ការប្រើប្រាស់សម្ភារឧបទេសក្នុងការរៀន និងបង្រៀន-២.១ សម្ភារឧបទេសក្នុងការរៀន និងបង្រៀន', 'មានសម្ភារឧបទេសសម្បូរបែប ឆ្លើយតបតាមតម្រូវការ និងសមត្ថភាពរបស់សិស្ស', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (111, 7, 'MATH', 'G1,G2,G3', 'LEVEL-1', 'radio', NULL, NULL, 'text', '២. ការប្រើប្រាស់សម្ភារឧបទេសក្នុងការរៀន និងបង្រៀន-២.២ ការប្រើប្រាស់សម្ភារឧបទេសក្នុងការកសាងបញ្ញត្តិ', 'គ្រូបានប្រើប្រាស់សម្ភារឧបទេសក្នុងការកសាងបញ្ញតិមិនទាន់បានត្រឹមត្រូវ', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (112, 8, 'MATH', 'G1,G2,G3', 'LEVEL-2', 'radio', NULL, NULL, 'text', '២. ការប្រើប្រាស់សម្ភារឧបទេសក្នុងការរៀន និងបង្រៀន-២.២ ការប្រើប្រាស់សម្ភារឧបទេសក្នុងការកសាងបញ្ញត្តិ', 'គ្រូបានប្រើប្រាស់សម្ភារឧបទេសក្នុងការកសាងបញ្ញត្តិផ្ដើមពីរូបី ទៅពាក់កណ្ដាលរូបី/ពាក់កណ្ដាលអរូបី ទៅអរូបីបានត្រឹមត្រូវ', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (113, 9, 'MATH', 'G1,G2,G3', 'LEVEL-3', 'radio', NULL, NULL, 'text', '២. ការប្រើប្រាស់សម្ភារឧបទេសក្នុងការរៀន និងបង្រៀន-២.២ ការប្រើប្រាស់សម្ភារឧបទេសក្នុងការកសាងបញ្ញត្តិ', 'គ្រូបានប្រើប្រាស់សម្ភារឧបទេសក្នុងការកសាងបញ្ញត្តិផ្ដើមពីរូបី ទៅពាក់កណ្ដាលរូបី/ពាក់កណ្ដាលអរូបី ទៅអរូបីបានត្រឹមត្រូវ និងស្របតាមសមត្ថភាពសិស្ស', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (114, 10, 'MATH', 'G1,G2,G3', 'LEVEL-1', 'radio', NULL, NULL, 'text', '៣. សកម្មភាពរៀន និងបង្រៀន-៣.១ ការប្រើប្រាស់សៀវភៅណែនាំគ្រូ', 'មិនអនុវត្តតាមសៀវភៅណែនាំគ្រូកម្រិតថ្នាក់ដំបូង', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (115, 11, 'MATH', 'G1,G2,G3', 'LEVEL-2', 'radio', NULL, NULL, 'text', '៣. សកម្មភាពរៀន និងបង្រៀន-៣.១ ការប្រើប្រាស់សៀវភៅណែនាំគ្រូ', 'អនុវត្តតាមសកម្មភាពដែលបានកំណត់ក្នុងសៀវភៅណែនាំគ្រូ', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (116, 12, 'MATH', 'G1,G2,G3', 'LEVEL-3', 'radio', NULL, NULL, 'text', '៣. សកម្មភាពរៀន និងបង្រៀន-៣.១ ការប្រើប្រាស់សៀវភៅណែនាំគ្រូ', 'អនុវត្តតាមសកម្មភាពដែលបានកំណត់ក្នុងសៀវភៅណែនាំគ្រូ ដោយមានភាពបត់បែន ច្នៃប្រឌិត និងសមស្របតាមបរិបទ', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (117, 13, 'MATH', 'G1,G2,G3', 'LEVEL-1', 'radio', NULL, NULL, 'text', '៣. សកម្មភាពរៀន និងបង្រៀន-៣.២. សមត្ថភាពមានស្រាប់របស់សិស្ស', 'សកម្មភាពបង្រៀនមិនទាន់ផ្អែកតាមសមត្ថភាពមានស្រាប់របស់សិស្ស', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (118, 14, 'MATH', 'G1,G2,G3', 'LEVEL-2', 'radio', NULL, NULL, 'text', '៣. សកម្មភាពរៀន និងបង្រៀន-៣.២. សមត្ថភាពមានស្រាប់របស់សិស្ស', 'សកម្មភាពបង្រៀនផ្អែកតាមសមត្ថភាពមានស្រាប់របស់សិស្ស', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (119, 15, 'MATH', 'G1,G2,G3', 'LEVEL-3', 'radio', NULL, NULL, 'text', '៣. សកម្មភាពរៀន និងបង្រៀន-៣.២. សមត្ថភាពមានស្រាប់របស់សិស្ស', 'សកម្មភាពបង្រៀនផ្អែកតាមសមត្ថភាពមានស្រាប់របស់សិស្សដែលជំរុញឱ្យសិស្សគិតបានរហ័ស', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (120, 16, 'MATH', 'G1,G2,G3', 'LEVEL-1', 'radio', NULL, NULL, 'text', '៣. សកម្មភាពរៀន និងបង្រៀន-៣.៣ អន្តរកម្ម', 'គ្រូនិងសិស្សមានអន្តរកម្ម គ្រូមានសកម្មភាពច្រើន ហើយ​សិស្សមាន​សកម្មភាព​តិចតួច', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (121, 17, 'MATH', 'G1,G2,G3', 'LEVEL-2', 'radio', NULL, NULL, 'text', '៣. សកម្មភាពរៀន និងបង្រៀន-៣.៣ អន្តរកម្ម', 'គ្រូនិងសិស្ស សិស្សនិងសិស្សមានអន្តរកម្ម ប៉ុន្តែគ្រូត្រួតពិនិត្យ​មិនបាន​គ្រប់​ជ្រុង​ជ្រោយ', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (122, 18, 'MATH', 'G1,G2,G3', 'LEVEL-3', 'radio', NULL, NULL, 'text', '៣. សកម្មភាពរៀន និងបង្រៀន-៣.៣ អន្តរកម្ម', 'គ្រូនិងសិស្ស សិស្សនិងសិស្សមានអន្តរកម្ម ហើយគ្រូត្រួតពិនិត្យបានគ្រប់​ជ្រុង​ជ្រោយ', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (123, 19, 'MATH', 'G1,G2,G3', 'LEVEL-1', 'radio', NULL, NULL, 'text', '៤. ការវាយតម្លៃ-៤.១. ការត្រួតពិនិត្យលើការយល់ដឹងរបស់សិស្ស', 'គ្រូសួរសំណួរ ឬដាក់កិច្ចការដោយ មិនបាន​ត្រួត​ពិនិត្យការយល់ដឹងរបស់សិស្ស', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (124, 20, 'MATH', 'G1,G2,G3', 'LEVEL-2', 'radio', NULL, NULL, 'text', '៤. ការវាយតម្លៃ-៤.១. ការត្រួតពិនិត្យលើការយល់ដឹងរបស់សិស្ស', 'គ្រូសួរសំណួរ ឬដាក់កិច្ចការ និងត្រួតពិនិត្យ ការយល់ដឹងរបស់សិស្ស តែមិនបានពិនិត្យគ្រប់ជ្រុងជ្រោយ', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (125, 21, 'MATH', 'G1,G2,G3', 'LEVEL-3', 'radio', NULL, NULL, 'text', '៤. ការវាយតម្លៃ-៤.១. ការត្រួតពិនិត្យលើការយល់ដឹងរបស់សិស្ស', 'គ្រូសួរសំណួរ ឬដាក់កិច្ចការ និងត្រួតពិនិត្យការយល់ដឹងរបស់សិស្សបាន​គ្រប់​ជ្រុងជ្រោយដោយប្រើ​វិធីសម្បូរបែប ។ ឧទា.៖បណ្ណភ្លើងសញ្ញាចរាចរ ក្តារឆ្នួន...', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (126, 22, 'MATH', 'G1,G2,G3', 'LEVEL-1', 'radio', NULL, NULL, 'text', '៤. ការវាយតម្លៃ-៤.២ ការជួយសិស្សដែលមានគំនិតភាន់ច្រឡំ ឬកំហុស', 'គ្រូយកចិត្តទុកដាក់លើគំនិតភាន់ច្រឡំ ឬកំហុស​របស់សិស្ស​ តែមិនបានកែលម្អ', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (127, 23, 'MATH', 'G1,G2,G3', 'LEVEL-2', 'radio', NULL, NULL, 'text', '៤. ការវាយតម្លៃ-៤.២ ការជួយសិស្សដែលមានគំនិតភាន់ច្រឡំ ឬកំហុស', 'គ្រូជួយសិស្សដោយពន្យល់ម្តងទៀត ឬចង្អុល​បង្ហាញពីដំណើរការពេលសិស្សមានគំនិតភាន់ច្រឡំ ឬកំហុស ប៉ុន្តែមិនបានឱ្យសិស្សបញ្ជាក់ពីមូលហេតុ', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (128, 24, 'MATH', 'G1,G2,G3', 'LEVEL-3', 'radio', NULL, NULL, 'text', '៤. ការវាយតម្លៃ-៤.២ ការជួយសិស្សដែលមានគំនិតភាន់ច្រឡំ ឬកំហុស', 'គ្រូបានឱ្យសិស្សបញ្ជាក់ពីមូលហេតុ ដែលនាំឱ្យមានគំនិតភាន់ច្រឡំឬកំហុស និងជួយពួកគេតាមវិធីផ្សេងៗប្រកបដោយប្រសិទ្ធភាពខ្ពស់', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (129, 25, 'MATH', 'G1,G2,G3', 'LEVEL-1', 'radio', NULL, NULL, 'text', '៤. ការវាយតម្លៃ-៤.៣ កម្រិតសំណួរ  ', 'សិស្សឆ្លើយបានត្រឹមសំណួរកម្រិតចងចាំ', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (131, 27, 'MATH', 'G1,G2,G3', 'LEVEL-3', 'radio', NULL, NULL, 'text', '៤. ការវាយតម្លៃ-៤.៣ កម្រិតសំណួរ  ', 'សិស្សឆ្លើយបានយ៉ាងហោចណាស់ត្រឹមសំណួរកម្រិតពិចារណាហ្មត់ចត់ (ចាប់ពីកម្រិតអនុវត្ត វិភាគ វាយតម្លៃ និងការបង្កើតថ្មី)', NULL);
INSERT INTO "public"."master_fields_123" ("id", "order", "subject", "grade", "level", "field_type_one", "field_type_two", "field_type_three", "field_type_four", "activity", "indicator", "note") VALUES (1, 1, 'KH', 'G1', 'LEVEL-1', 'radio', NULL, NULL, 'text', 'ការរំឭកមេរៀន', '១. ប្រើប្រាស់សៀវភៅណែនាំគ្រូ(អនុវតជំហានសកម្មភាពតាមលំដាប់លំដោយ) ដែរឬទេ?', NULL);
COMMIT;

-- ----------------------------
-- Primary Key structure for table master_fields_123
-- ----------------------------
ALTER TABLE "public"."master_fields_123" ADD CONSTRAINT "master_fields_123_pkey" PRIMARY KEY ("id");
